name: Home application

on:
  push:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_PACKAGE_PUBLISH}}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@main
        with:
          versionSpec: '5.10.3'
      - name: Invoke GitVersion
        uses: gittools/actions/gitversion/execute@main
        id: gitversion

